### ISSUE TITLE
TypeError: socialMedia is undefined

### ISSUE THREAD

**Issue by dBianchii** [harshgoel05/another-portfolio#112]
This is happening when I run `yarn dev`

**To Reproduce**
1. `yarn dev`

**Screenshots**
![image](https://user-images.githubusercontent.com/17372417/161342761-1c99187f-632f-4b5a-93d9-274f53c807f6.png)

 - OS: [Windows]
 - Browser [firefox]

**Additional context**

Here's the full console output:
![image](https://user-images.githubusercontent.com/17372417/161342887-d2bebffe-554e-4477-a309-ccd479c4c6ee.png)

**Comment by harshgoel05** [comment]
Please refer https://github.com/harshgoel05/another-portfolio/issues/104#issuecomment-984719901

**Comment by dBianchii** [comment]
I realized afterwards that that's what you need to do. Sorry 😶

**Comment by harshgoel05** [comment]
No worries, glad that its working. Closing the  issue.
