### ISSUE TITLE
client-side application error

### ISSUE THREAD

**Issue by ladunjexa** [harshgoel05/another-portfolio#114]
Problem solved.

**Comment by harshgoel05** [comment]
thanks, sorry for being late to reply.
Also, that's a common error people see, do you mind creating a discussion for that and putting up how you fixed it?

**Comment by ladunjexa** [comment]
Hi harsh, At first I thought it was libraries that were not up to date, any embed client-side script or prevent from being published (for ex. `private` key in package.json) but after I didn't find an ideal solution, then I just reprogrammed the whole site - because I really connected with the design and it was done in TailwindCSS so it makes it easier to reprogram.

In any case, in my humble opinion the code is supported by libraries that have not been updated for a long time and the error that is received is the result of a lack of browser support - so it is worth trying to update third-party scripts and libraries individually and see if a change has been made.
If I have time, I'll try to play with it some more and if I find a solution I'll update about it.
 
btw, outstanding work!
