### ISSUE TITLE
Add Toasts

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/another-portfolio#45]
Add toasts on custom events
- scrolling through projects
- opening some specific page
- etc

**Comment by iamyashkhandelwal** [comment]
Hey @harshgoel05 
I would like to contribute to this issue. Can you please elaborate it a little, I couldn't got the 1st point.

**Comment by harshgoel05** [comment]
Ignore this one please, was planning something which i dropped. Thanks.
