### ISSUE TITLE
Different Highlight color

### ISSUE THREAD

**Issue by govarun** [harshgoel05/another-portfolio#80]
**Describe the bug**
Just highlighted some text on the first page, and the color matched with the text color, and made it unreadable. That's a bit weird only if not done consciously

**Screenshots**
![Screen Shot 2021-07-11 at 7 08 29 PM](https://user-images.githubusercontent.com/42479771/125197544-d35eeb00-e27b-11eb-9e15-da513ed04c4b.png)

**Comment by harshgoel05** [comment]
Thanks for raising the issue! It has been fixed in the PR #81
