### ISSUE TITLE
Word wrap break in GitHub section

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/another-portfolio#84]
Bug:

The word supercalifragilisticexpialidocious breaks the UI.the p tag should have word wrap break so that it goes in next line.

![Screenshot_2021-08-14-10-23-38-17](https://user-images.githubusercontent.com/48649088/129434538-a0785441-122e-4de6-b3aa-932a706b2700.jpg)

**Comment by SneakySensei** [comment]
Hi. I'd like to pick this up!

**Comment by harshgoel05** [comment]
For sure, go ahead sir! :)
