### ISSUE TITLE
Font size changes | Work Experience

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/another-portfolio#91]
**Describe the bug**
The work experience section (https://harshgoel.me/work) doesn't have proper text sizing. The dates should be smaller and the designation should be bigger

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48649088/135571308-c80774e7-1680-42dd-8266-062d29a7bcea.png)

**Comment by bhimeshagrawal** [comment]
Hey @harshgoel05 , can I work on this issue ? Please assign me this

**Comment by harshgoel05** [comment]
Hey @bhimeshagrawal , go ahead! 👯

**Comment by dulcetsoul** [comment]
Hey @harshgoel05 if not done. Could I take up the issue ?

**Comment by harshgoel05** [comment]
@dulcetsoul sure!

**Comment by GaushJ** [comment]
Hey @harshgoel05  if this issue is unresolved , can you assign this to me?

**Comment by harshgoel05** [comment]
Go ahead @GaushJ , please acknowledge once you start so that I will assign it to you!

**Comment by GaushJ** [comment]
I have forked this repo , am working on it . Kindly assign

**Comment by GaushJ** [comment]
Hey @harshgoel05 I found the solution of the problem but unable to run it locally . Here's what I did,
Cloned the repo after forking , ran yarn in terminal , fixed the font size then ran yarn build in terminal. After successful build  I ran yarn dev but it shows error in the browse
![Capture355](https://user-images.githubusercontent.com/53349226/135720535-2dd11c62-948d-422d-bf9a-dac9c3f71641.PNG)
![Capture234234](https://user-images.githubusercontent.com/53349226/135720538-32ccf436-ee1b-4277-847b-2f93281484c3.PNG)
r.

**Comment by harshgoel05** [comment]
Hello,
Please add a .env as per .env.example @GaushJ

**Comment by GaushJ** [comment]
MONGODB_URI = <MONGODB_URI> ( put a mongodb url here)
BASE_URL = http://localhost:3000  (this is my api URL, change it to http://localhost:3000, in case you tend to use your database)
ENV = <production || development> (environment)

I have no idea about it but I can show you what I did so you could check on your local ,machine
![Capture355](https://user-images.githubusercontent.com/53349226/135722614-ef7d1316-0cff-4739-b342-25421ba3677f.PNG)

**Comment by GaushJ** [comment]
@harshgoel05 I changed text-sm to text-base idk if that's right .

**Comment by harshgoel05** [comment]
You need to make a file called `.env` in root with content as:

`BASE_URL = https://harshgoel.me`

**Comment by GaushJ** [comment]
It didn't work . I made a .env file called newuser.env and pasted BASE_URL you gave but it still showing error
![newfile env](https://user-images.githubusercontent.com/53349226/135728224-bee7724c-d93b-4992-85c6-9cbccf951e47.PNG)

**Comment by GaushJ** [comment]
@harshgoel05 What am I doing wrong?

**Comment by harshgoel05** [comment]
The name will be just '.env'

Its an environment file.

**Comment by GaushJ** [comment]
@harshgoel05 It Worked !! , would you mind explaining in brief how it worked ? P.S The font size increased so will be starting a pull request soon.

**Comment by harshgoel05** [comment]
https://nextjs.org/docs/basic-features/environment-variables

This will give you an idea.

**Comment by GaushJ** [comment]
Hey @harshgoel05 I have created a pull request .

**Comment by harshgoel05** [comment]
Closed by #97
